name: CI

on:
  push:
  pull_request:

jobs:
  pipeline-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run extract
        run: python src/extract/extract_source.py

      - name: Run transform
        run: python src/transform/clean_ratings.py

      - name: Verify processed output exists
        run: |
          test -f data/processed/clean_ratings.csv
          echo "✅ clean_ratings.csv found."
